on:
  push:
    branches:
      - "main"
  pull_request:

name: "CI"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  ci:
    uses: "WebProject-xyz/.github/.github/workflows/ci.yml@main"
    secrets: inherit
    with:
      php-version: "8.5"
      php-cs-fixer-ignore-env: true
      test-matrix: |
        [
          {"php-version": "8.5", "dependencies": "locked", "with_coverage": true}
        ]
