name: Release
"on":
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main
permissions:
  contents: read # for checkout
jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      actions: write # trigger after tag push
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16 # v5.0.0
        with:
          tag_format: ${version}
          branches: |
            ['main', 'next']
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Docker Build
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1
        with:
          workflow: Build and Push Docker Image
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: >
            {
              "version": "${{ steps.semantic.outputs.new_release_git_tag }}"
            }
